name: barcode_scanner
description: A Flutter plugin to implement google's standalone ml kit made for mobile platform.
version: 0.0.1
homepage: https://github.com/MarioJunio/flutter-barcode-scanner-plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.google_ml_kit
        pluginClass: GoogleMlKitPlugin
      ios:
        pluginClass: GoogleMlKitPlugin
